### ISSUE TITLE
Maybe a summary line would be nice

### ISSUE THREAD

**Issue by sassman** [lukehsiao/git-stats#34]
I just found your tool and it is awesome, it does what it offers very quickly. Good job!

However, I thought it would be nice to show a `Totals` line below all the Authors that would summarize the columns. I guess a simple sum for every column would be good enough.

The summary line could be only enabled by a cli arg like `-s|--show-totals`, but I would not mind having it as default.

**Comment by lukehsiao** [comment]
This is now part of [`v0.1.10`](https://github.com/lukehsiao/git-stats/releases/tag/v0.1.10)

**Comment by sassman** [comment]
Thanks a lot, that was super quick!! Works all as expected. ❤️
