### ISSUE TITLE
[feature request] sort by other columns

### ISSUE THREAD

**Issue by travischambers** [lukehsiao/git-stats#36]
The default sort by `commits` is great, but i want to sort by net changes. 😁

**Comment by lukehsiao** [comment]
For some context, [git shortlog](https://git-scm.com/docs/git-shortlog) can be sorted by either commits or author name. We're currently just using `-n` to get it by commits, `git-stats` isn't doing any sorting itself.

That said, I suspect this is pretty trivial to implement (just adding an option to sort by an enum, and run that sort on the vector before we print it).

Going to take a swing at an implementation soon.

**Comment by lukehsiao** [comment]
This in released in [`v0.1.14`](https://github.com/lukehsiao/git-stats/releases/tag/v0.1.14).
